services:
  - type: web
    name: smart-attendance-system
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: iattend
          property: connectionString
      - key: NODE_ENV
        value: production
